/*
Navicat PGSQL Data Transfer

Source Server         : localhost
Source Server Version : 90305
Source Host           : localhost:5432
Source Database       : etrans_final
Source Schema         : public

Target Server Type    : PGSQL
Target Server Version : 90305
File Encoding         : 65001

Date: 2015-06-01 14:41:19
*/


-- ----------------------------
-- Table structure for region
-- ----------------------------
DROP TABLE IF EXISTS "public"."region";
CREATE TABLE "public"."region" (
"regionid" int8 NOT NULL,
"countryid" int8,
"regioncode" varchar(75) COLLATE "default",
"name" varchar(75) COLLATE "default",
"active_" bool
)
WITH (OIDS=FALSE)

;

-- ----------------------------
-- Records of region
-- ----------------------------
INSERT INTO "public"."region" VALUES ('1001', '1', 'AB', 'Alberta', 't');
INSERT INTO "public"."region" VALUES ('1002', '1', 'BC', 'British Columbia', 't');
INSERT INTO "public"."region" VALUES ('1003', '1', 'MB', 'Manitoba', 't');
INSERT INTO "public"."region" VALUES ('1004', '1', 'NB', 'New Brunswick', 't');
INSERT INTO "public"."region" VALUES ('1005', '1', 'NL', 'Newfoundland and Labrador', 't');
INSERT INTO "public"."region" VALUES ('1006', '1', 'NT', 'Northwest Territories', 't');
INSERT INTO "public"."region" VALUES ('1007', '1', 'NS', 'Nova Scotia', 't');
INSERT INTO "public"."region" VALUES ('1008', '1', 'NU', 'Nunavut', 't');
INSERT INTO "public"."region" VALUES ('1009', '1', 'ON', 'Ontario', 't');
INSERT INTO "public"."region" VALUES ('1010', '1', 'PE', 'Prince Edward Island', 't');
INSERT INTO "public"."region" VALUES ('1011', '1', 'QC', 'Quebec', 't');
INSERT INTO "public"."region" VALUES ('1012', '1', 'SK', 'Saskatchewan', 't');
INSERT INTO "public"."region" VALUES ('1013', '1', 'YT', 'Yukon', 't');
INSERT INTO "public"."region" VALUES ('2001', '2', 'CN-34', 'Anhui', 't');
INSERT INTO "public"."region" VALUES ('2002', '2', 'CN-92', 'Aomen', 't');
INSERT INTO "public"."region" VALUES ('2003', '2', 'CN-11', 'Beijing', 't');
INSERT INTO "public"."region" VALUES ('2004', '2', 'CN-50', 'Chongqing', 't');
INSERT INTO "public"."region" VALUES ('2005', '2', 'CN-35', 'Fujian', 't');
INSERT INTO "public"."region" VALUES ('2006', '2', 'CN-62', 'Gansu', 't');
INSERT INTO "public"."region" VALUES ('2007', '2', 'CN-44', 'Guangdong', 't');
INSERT INTO "public"."region" VALUES ('2008', '2', 'CN-45', 'Guangxi', 't');
INSERT INTO "public"."region" VALUES ('2009', '2', 'CN-52', 'Guizhou', 't');
INSERT INTO "public"."region" VALUES ('2010', '2', 'CN-46', 'Hainan', 't');
INSERT INTO "public"."region" VALUES ('2011', '2', 'CN-13', 'Hebei', 't');
INSERT INTO "public"."region" VALUES ('2012', '2', 'CN-23', 'Heilongjiang', 't');
INSERT INTO "public"."region" VALUES ('2013', '2', 'CN-41', 'Henan', 't');
INSERT INTO "public"."region" VALUES ('2014', '2', 'CN-42', 'Hubei', 't');
INSERT INTO "public"."region" VALUES ('2015', '2', 'CN-43', 'Hunan', 't');
INSERT INTO "public"."region" VALUES ('2016', '2', 'CN-32', 'Jiangsu', 't');
INSERT INTO "public"."region" VALUES ('2017', '2', 'CN-36', 'Jiangxi', 't');
INSERT INTO "public"."region" VALUES ('2018', '2', 'CN-22', 'Jilin', 't');
INSERT INTO "public"."region" VALUES ('2019', '2', 'CN-21', 'Liaoning', 't');
INSERT INTO "public"."region" VALUES ('2020', '2', 'CN-15', 'Nei Mongol', 't');
INSERT INTO "public"."region" VALUES ('2021', '2', 'CN-64', 'Ningxia', 't');
INSERT INTO "public"."region" VALUES ('2022', '2', 'CN-63', 'Qinghai', 't');
INSERT INTO "public"."region" VALUES ('2023', '2', 'CN-61', 'Shaanxi', 't');
INSERT INTO "public"."region" VALUES ('2024', '2', 'CN-37', 'Shandong', 't');
INSERT INTO "public"."region" VALUES ('2025', '2', 'CN-31', 'Shanghai', 't');
INSERT INTO "public"."region" VALUES ('2026', '2', 'CN-14', 'Shanxi', 't');
INSERT INTO "public"."region" VALUES ('2027', '2', 'CN-51', 'Sichuan', 't');
INSERT INTO "public"."region" VALUES ('2028', '2', 'CN-71', 'Taiwan', 't');
INSERT INTO "public"."region" VALUES ('2029', '2', 'CN-12', 'Tianjin', 't');
INSERT INTO "public"."region" VALUES ('2030', '2', 'CN-91', 'Xianggang', 't');
INSERT INTO "public"."region" VALUES ('2031', '2', 'CN-65', 'Xinjiang', 't');
INSERT INTO "public"."region" VALUES ('2032', '2', 'CN-54', 'Xizang', 't');
INSERT INTO "public"."region" VALUES ('2033', '2', 'CN-53', 'Yunnan', 't');
INSERT INTO "public"."region" VALUES ('2034', '2', 'CN-33', 'Zhejiang', 't');
INSERT INTO "public"."region" VALUES ('3001', '3', 'A', 'Alsace', 't');
INSERT INTO "public"."region" VALUES ('3002', '3', 'B', 'Aquitaine', 't');
INSERT INTO "public"."region" VALUES ('3003', '3', 'C', 'Auvergne', 't');
INSERT INTO "public"."region" VALUES ('3004', '3', 'P', 'Basse-Normandie', 't');
INSERT INTO "public"."region" VALUES ('3005', '3', 'D', 'Bourgogne', 't');
INSERT INTO "public"."region" VALUES ('3006', '3', 'E', 'Bretagne', 't');
INSERT INTO "public"."region" VALUES ('3007', '3', 'F', 'Centre', 't');
INSERT INTO "public"."region" VALUES ('3008', '3', 'G', 'Champagne-Ardenne', 't');
INSERT INTO "public"."region" VALUES ('3009', '3', 'H', 'Corse', 't');
INSERT INTO "public"."region" VALUES ('3010', '3', 'GF', 'Guyane', 't');
INSERT INTO "public"."region" VALUES ('3011', '3', 'I', 'Franche Comté', 't');
INSERT INTO "public"."region" VALUES ('3012', '3', 'GP', 'Guadeloupe', 't');
INSERT INTO "public"."region" VALUES ('3013', '3', 'Q', 'Haute-Normandie', 't');
INSERT INTO "public"."region" VALUES ('3014', '3', 'J', 'Île-de-France', 't');
INSERT INTO "public"."region" VALUES ('3015', '3', 'K', 'Languedoc-Roussillon', 't');
INSERT INTO "public"."region" VALUES ('3016', '3', 'L', 'Limousin', 't');
INSERT INTO "public"."region" VALUES ('3017', '3', 'M', 'Lorraine', 't');
INSERT INTO "public"."region" VALUES ('3018', '3', 'MQ', 'Martinique', 't');
INSERT INTO "public"."region" VALUES ('3019', '3', 'N', 'Midi-Pyrénées', 't');
INSERT INTO "public"."region" VALUES ('3020', '3', 'O', 'Nord Pas de Calais', 't');
INSERT INTO "public"."region" VALUES ('3021', '3', 'R', 'Pays de la Loire', 't');
INSERT INTO "public"."region" VALUES ('3022', '3', 'S', 'Picardie', 't');
INSERT INTO "public"."region" VALUES ('3023', '3', 'T', 'Poitou-Charentes', 't');
INSERT INTO "public"."region" VALUES ('3024', '3', 'U', 'Provence-Alpes-Côte-d''Azur', 't');
INSERT INTO "public"."region" VALUES ('3025', '3', 'RE', 'Réunion', 't');
INSERT INTO "public"."region" VALUES ('3026', '3', 'V', 'Rhône-Alpes', 't');
INSERT INTO "public"."region" VALUES ('4001', '4', 'BW', 'Baden-Württemberg', 't');
INSERT INTO "public"."region" VALUES ('4002', '4', 'BY', 'Bayern', 't');
INSERT INTO "public"."region" VALUES ('4003', '4', 'BE', 'Berlin', 't');
INSERT INTO "public"."region" VALUES ('4004', '4', 'BB', 'Brandenburg', 't');
INSERT INTO "public"."region" VALUES ('4005', '4', 'HB', 'Bremen', 't');
INSERT INTO "public"."region" VALUES ('4006', '4', 'HH', 'Hamburg', 't');
INSERT INTO "public"."region" VALUES ('4007', '4', 'HE', 'Hessen', 't');
INSERT INTO "public"."region" VALUES ('4008', '4', 'MV', 'Mecklenburg-Vorpommern', 't');
INSERT INTO "public"."region" VALUES ('4009', '4', 'NI', 'Niedersachsen', 't');
INSERT INTO "public"."region" VALUES ('4010', '4', 'NW', 'Nordrhein-Westfalen', 't');
INSERT INTO "public"."region" VALUES ('4011', '4', 'RP', 'Rheinland-Pfalz', 't');
INSERT INTO "public"."region" VALUES ('4012', '4', 'SL', 'Saarland', 't');
INSERT INTO "public"."region" VALUES ('4013', '4', 'SN', 'Sachsen', 't');
INSERT INTO "public"."region" VALUES ('4014', '4', 'ST', 'Sachsen-Anhalt', 't');
INSERT INTO "public"."region" VALUES ('4015', '4', 'SH', 'Schleswig-Holstein', 't');
INSERT INTO "public"."region" VALUES ('4016', '4', 'TH', 'Thüringen', 't');
INSERT INTO "public"."region" VALUES ('8001', '8', 'AG', 'Agrigento', 't');
INSERT INTO "public"."region" VALUES ('8002', '8', 'AL', 'Alessandria', 't');
INSERT INTO "public"."region" VALUES ('8003', '8', 'AN', 'Ancona', 't');
INSERT INTO "public"."region" VALUES ('8004', '8', 'AO', 'Aosta', 't');
INSERT INTO "public"."region" VALUES ('8005', '8', 'AR', 'Arezzo', 't');
INSERT INTO "public"."region" VALUES ('8006', '8', 'AP', 'Ascoli Piceno', 't');
INSERT INTO "public"."region" VALUES ('8007', '8', 'AT', 'Asti', 't');
INSERT INTO "public"."region" VALUES ('8008', '8', 'AV', 'Avellino', 't');
INSERT INTO "public"."region" VALUES ('8009', '8', 'BA', 'Bari', 't');
INSERT INTO "public"."region" VALUES ('8010', '8', 'BT', 'Barletta-Andria-Trani', 't');
INSERT INTO "public"."region" VALUES ('8011', '8', 'BL', 'Belluno', 't');
INSERT INTO "public"."region" VALUES ('8012', '8', 'BN', 'Benevento', 't');
INSERT INTO "public"."region" VALUES ('8013', '8', 'BG', 'Bergamo', 't');
INSERT INTO "public"."region" VALUES ('8014', '8', 'BI', 'Biella', 't');
INSERT INTO "public"."region" VALUES ('8015', '8', 'BO', 'Bologna', 't');
INSERT INTO "public"."region" VALUES ('8016', '8', 'BZ', 'Bolzano', 't');
INSERT INTO "public"."region" VALUES ('8017', '8', 'BS', 'Brescia', 't');
INSERT INTO "public"."region" VALUES ('8018', '8', 'BR', 'Brindisi', 't');
INSERT INTO "public"."region" VALUES ('8019', '8', 'CA', 'Cagliari', 't');
INSERT INTO "public"."region" VALUES ('8020', '8', 'CL', 'Caltanissetta', 't');
INSERT INTO "public"."region" VALUES ('8021', '8', 'CB', 'Campobasso', 't');
INSERT INTO "public"."region" VALUES ('8022', '8', 'CI', 'Carbonia-Iglesias', 't');
INSERT INTO "public"."region" VALUES ('8023', '8', 'CE', 'Caserta', 't');
INSERT INTO "public"."region" VALUES ('8024', '8', 'CT', 'Catania', 't');
INSERT INTO "public"."region" VALUES ('8025', '8', 'CZ', 'Catanzaro', 't');
INSERT INTO "public"."region" VALUES ('8026', '8', 'CH', 'Chieti', 't');
INSERT INTO "public"."region" VALUES ('8027', '8', 'CO', 'Como', 't');
INSERT INTO "public"."region" VALUES ('8028', '8', 'CS', 'Cosenza', 't');
INSERT INTO "public"."region" VALUES ('8029', '8', 'CR', 'Cremona', 't');
INSERT INTO "public"."region" VALUES ('8030', '8', 'KR', 'Crotone', 't');
INSERT INTO "public"."region" VALUES ('8031', '8', 'CN', 'Cuneo', 't');
INSERT INTO "public"."region" VALUES ('8032', '8', 'EN', 'Enna', 't');
INSERT INTO "public"."region" VALUES ('8033', '8', 'FM', 'Fermo', 't');
INSERT INTO "public"."region" VALUES ('8034', '8', 'FE', 'Ferrara', 't');
INSERT INTO "public"."region" VALUES ('8035', '8', 'FI', 'Firenze', 't');
INSERT INTO "public"."region" VALUES ('8036', '8', 'FG', 'Foggia', 't');
INSERT INTO "public"."region" VALUES ('8037', '8', 'FC', 'Forli-Cesena', 't');
INSERT INTO "public"."region" VALUES ('8038', '8', 'FR', 'Frosinone', 't');
INSERT INTO "public"."region" VALUES ('8039', '8', 'GE', 'Genova', 't');
INSERT INTO "public"."region" VALUES ('8040', '8', 'GO', 'Gorizia', 't');
INSERT INTO "public"."region" VALUES ('8041', '8', 'GR', 'Grosseto', 't');
INSERT INTO "public"."region" VALUES ('8042', '8', 'IM', 'Imperia', 't');
INSERT INTO "public"."region" VALUES ('8043', '8', 'IS', 'Isernia', 't');
INSERT INTO "public"."region" VALUES ('8044', '8', 'AQ', 'L''Aquila', 't');
INSERT INTO "public"."region" VALUES ('8045', '8', 'SP', 'La Spezia', 't');
INSERT INTO "public"."region" VALUES ('8046', '8', 'LT', 'Latina', 't');
INSERT INTO "public"."region" VALUES ('8047', '8', 'LE', 'Lecce', 't');
INSERT INTO "public"."region" VALUES ('8048', '8', 'LC', 'Lecco', 't');
INSERT INTO "public"."region" VALUES ('8049', '8', 'LI', 'Livorno', 't');
INSERT INTO "public"."region" VALUES ('8050', '8', 'LO', 'Lodi', 't');
INSERT INTO "public"."region" VALUES ('8051', '8', 'LU', 'Lucca', 't');
INSERT INTO "public"."region" VALUES ('8052', '8', 'MC', 'Macerata', 't');
INSERT INTO "public"."region" VALUES ('8053', '8', 'MN', 'Mantova', 't');
INSERT INTO "public"."region" VALUES ('8054', '8', 'MS', 'Massa-Carrara', 't');
INSERT INTO "public"."region" VALUES ('8055', '8', 'MT', 'Matera', 't');
INSERT INTO "public"."region" VALUES ('8056', '8', 'MA', 'Medio Campidano', 't');
INSERT INTO "public"."region" VALUES ('8057', '8', 'ME', 'Messina', 't');
INSERT INTO "public"."region" VALUES ('8058', '8', 'MI', 'Milano', 't');
INSERT INTO "public"."region" VALUES ('8059', '8', 'MO', 'Modena', 't');
INSERT INTO "public"."region" VALUES ('8060', '8', 'MB', 'Monza e Brianza', 't');
INSERT INTO "public"."region" VALUES ('8061', '8', 'NA', 'Napoli', 't');
INSERT INTO "public"."region" VALUES ('8062', '8', 'NO', 'Novara', 't');
INSERT INTO "public"."region" VALUES ('8063', '8', 'NU', 'Nuoro', 't');
INSERT INTO "public"."region" VALUES ('8064', '8', 'OG', 'Ogliastra', 't');
INSERT INTO "public"."region" VALUES ('8065', '8', 'OT', 'Olbia-Tempio', 't');
INSERT INTO "public"."region" VALUES ('8066', '8', 'OR', 'Oristano', 't');
INSERT INTO "public"."region" VALUES ('8067', '8', 'PD', 'Padova', 't');
INSERT INTO "public"."region" VALUES ('8068', '8', 'PA', 'Palermo', 't');
INSERT INTO "public"."region" VALUES ('8069', '8', 'PR', 'Parma', 't');
INSERT INTO "public"."region" VALUES ('8070', '8', 'PV', 'Pavia', 't');
INSERT INTO "public"."region" VALUES ('8071', '8', 'PG', 'Perugia', 't');
INSERT INTO "public"."region" VALUES ('8072', '8', 'PU', 'Pesaro e Urbino', 't');
INSERT INTO "public"."region" VALUES ('8073', '8', 'PE', 'Pescara', 't');
INSERT INTO "public"."region" VALUES ('8074', '8', 'PC', 'Piacenza', 't');
INSERT INTO "public"."region" VALUES ('8075', '8', 'PI', 'Pisa', 't');
INSERT INTO "public"."region" VALUES ('8076', '8', 'PT', 'Pistoia', 't');
INSERT INTO "public"."region" VALUES ('8077', '8', 'PN', 'Pordenone', 't');
INSERT INTO "public"."region" VALUES ('8078', '8', 'PZ', 'Potenza', 't');
INSERT INTO "public"."region" VALUES ('8079', '8', 'PO', 'Prato', 't');
INSERT INTO "public"."region" VALUES ('8080', '8', 'RG', 'Ragusa', 't');
INSERT INTO "public"."region" VALUES ('8081', '8', 'RA', 'Ravenna', 't');
INSERT INTO "public"."region" VALUES ('8082', '8', 'RC', 'Reggio Calabria', 't');
INSERT INTO "public"."region" VALUES ('8083', '8', 'RE', 'Reggio Emilia', 't');
INSERT INTO "public"."region" VALUES ('8084', '8', 'RI', 'Rieti', 't');
INSERT INTO "public"."region" VALUES ('8085', '8', 'RN', 'Rimini', 't');
INSERT INTO "public"."region" VALUES ('8086', '8', 'RM', 'Roma', 't');
INSERT INTO "public"."region" VALUES ('8087', '8', 'RO', 'Rovigo', 't');
INSERT INTO "public"."region" VALUES ('8088', '8', 'SA', 'Salerno', 't');
INSERT INTO "public"."region" VALUES ('8089', '8', 'SS', 'Sassari', 't');
INSERT INTO "public"."region" VALUES ('8090', '8', 'SV', 'Savona', 't');
INSERT INTO "public"."region" VALUES ('8091', '8', 'SI', 'Siena', 't');
INSERT INTO "public"."region" VALUES ('8092', '8', 'SR', 'Siracusa', 't');
INSERT INTO "public"."region" VALUES ('8093', '8', 'SO', 'Sondrio', 't');
INSERT INTO "public"."region" VALUES ('8094', '8', 'TA', 'Taranto', 't');
INSERT INTO "public"."region" VALUES ('8095', '8', 'TE', 'Teramo', 't');
INSERT INTO "public"."region" VALUES ('8096', '8', 'TR', 'Terni', 't');
INSERT INTO "public"."region" VALUES ('8097', '8', 'TO', 'Torino', 't');
INSERT INTO "public"."region" VALUES ('8098', '8', 'TP', 'Trapani', 't');
INSERT INTO "public"."region" VALUES ('8099', '8', 'TN', 'Trento', 't');
INSERT INTO "public"."region" VALUES ('8100', '8', 'TV', 'Treviso', 't');
INSERT INTO "public"."region" VALUES ('8101', '8', 'TS', 'Trieste', 't');
INSERT INTO "public"."region" VALUES ('8102', '8', 'UD', 'Udine', 't');
INSERT INTO "public"."region" VALUES ('8103', '8', 'VA', 'Varese', 't');
INSERT INTO "public"."region" VALUES ('8104', '8', 'VE', 'Venezia', 't');
INSERT INTO "public"."region" VALUES ('8105', '8', 'VB', 'Verbano-Cusio-Ossola', 't');
INSERT INTO "public"."region" VALUES ('8106', '8', 'VC', 'Vercelli', 't');
INSERT INTO "public"."region" VALUES ('8107', '8', 'VR', 'Verona', 't');
INSERT INTO "public"."region" VALUES ('8108', '8', 'VV', 'Vibo Valentia', 't');
INSERT INTO "public"."region" VALUES ('8109', '8', 'VI', 'Vicenza', 't');
INSERT INTO "public"."region" VALUES ('8110', '8', 'VT', 'Viterbo', 't');
INSERT INTO "public"."region" VALUES ('11001', '11', 'DR', 'Drenthe', 't');
INSERT INTO "public"."region" VALUES ('11002', '11', 'FL', 'Flevoland', 't');
INSERT INTO "public"."region" VALUES ('11003', '11', 'FR', 'Friesland', 't');
INSERT INTO "public"."region" VALUES ('11004', '11', 'GE', 'Gelderland', 't');
INSERT INTO "public"."region" VALUES ('11005', '11', 'GR', 'Groningen', 't');
INSERT INTO "public"."region" VALUES ('11006', '11', 'LI', 'Limburg', 't');
INSERT INTO "public"."region" VALUES ('11007', '11', 'NB', 'Noord-Brabant', 't');
INSERT INTO "public"."region" VALUES ('11008', '11', 'NH', 'Noord-Holland', 't');
INSERT INTO "public"."region" VALUES ('11009', '11', 'OV', 'Overijssel', 't');
INSERT INTO "public"."region" VALUES ('11010', '11', 'UT', 'Utrecht', 't');
INSERT INTO "public"."region" VALUES ('11011', '11', 'ZE', 'Zeeland', 't');
INSERT INTO "public"."region" VALUES ('11012', '11', 'ZH', 'Zuid-Holland', 't');
INSERT INTO "public"."region" VALUES ('15001', '15', 'AN', 'Andalusia', 't');
INSERT INTO "public"."region" VALUES ('15002', '15', 'AR', 'Aragon', 't');
INSERT INTO "public"."region" VALUES ('15003', '15', 'AS', 'Asturias', 't');
INSERT INTO "public"."region" VALUES ('15004', '15', 'IB', 'Balearic Islands', 't');
INSERT INTO "public"."region" VALUES ('15005', '15', 'PV', 'Basque Country', 't');
INSERT INTO "public"."region" VALUES ('15006', '15', 'CN', 'Canary Islands', 't');
INSERT INTO "public"."region" VALUES ('15007', '15', 'CB', 'Cantabria', 't');
INSERT INTO "public"."region" VALUES ('15008', '15', 'CL', 'Castile and Leon', 't');
INSERT INTO "public"."region" VALUES ('15009', '15', 'CM', 'Castile-La Mancha', 't');
INSERT INTO "public"."region" VALUES ('15010', '15', 'CT', 'Catalonia', 't');
INSERT INTO "public"."region" VALUES ('15011', '15', 'CE', 'Ceuta', 't');
INSERT INTO "public"."region" VALUES ('15012', '15', 'EX', 'Extremadura', 't');
INSERT INTO "public"."region" VALUES ('15013', '15', 'GA', 'Galicia', 't');
INSERT INTO "public"."region" VALUES ('15014', '15', 'LO', 'La Rioja', 't');
INSERT INTO "public"."region" VALUES ('15015', '15', 'M', 'Madrid', 't');
INSERT INTO "public"."region" VALUES ('15016', '15', 'ML', 'Melilla', 't');
INSERT INTO "public"."region" VALUES ('15017', '15', 'MU', 'Murcia', 't');
INSERT INTO "public"."region" VALUES ('15018', '15', 'NA', 'Navarra', 't');
INSERT INTO "public"."region" VALUES ('15019', '15', 'VC', 'Valencia', 't');
INSERT INTO "public"."region" VALUES ('19001', '19', 'AL', 'Alabama', 't');
INSERT INTO "public"."region" VALUES ('19002', '19', 'AK', 'Alaska', 't');
INSERT INTO "public"."region" VALUES ('19003', '19', 'AZ', 'Arizona', 't');
INSERT INTO "public"."region" VALUES ('19004', '19', 'AR', 'Arkansas', 't');
INSERT INTO "public"."region" VALUES ('19005', '19', 'CA', 'California', 't');
INSERT INTO "public"."region" VALUES ('19006', '19', 'CO', 'Colorado', 't');
INSERT INTO "public"."region" VALUES ('19007', '19', 'CT', 'Connecticut', 't');
INSERT INTO "public"."region" VALUES ('19008', '19', 'DC', 'District of Columbia', 't');
INSERT INTO "public"."region" VALUES ('19009', '19', 'DE', 'Delaware', 't');
INSERT INTO "public"."region" VALUES ('19010', '19', 'FL', 'Florida', 't');
INSERT INTO "public"."region" VALUES ('19011', '19', 'GA', 'Georgia', 't');
INSERT INTO "public"."region" VALUES ('19012', '19', 'HI', 'Hawaii', 't');
INSERT INTO "public"."region" VALUES ('19013', '19', 'ID', 'Idaho', 't');
INSERT INTO "public"."region" VALUES ('19014', '19', 'IL', 'Illinois', 't');
INSERT INTO "public"."region" VALUES ('19015', '19', 'IN', 'Indiana', 't');
INSERT INTO "public"."region" VALUES ('19016', '19', 'IA', 'Iowa', 't');
INSERT INTO "public"."region" VALUES ('19017', '19', 'KS', 'Kansas', 't');
INSERT INTO "public"."region" VALUES ('19018', '19', 'KY', 'Kentucky ', 't');
INSERT INTO "public"."region" VALUES ('19019', '19', 'LA', 'Louisiana ', 't');
INSERT INTO "public"."region" VALUES ('19020', '19', 'ME', 'Maine', 't');
INSERT INTO "public"."region" VALUES ('19021', '19', 'MD', 'Maryland', 't');
INSERT INTO "public"."region" VALUES ('19022', '19', 'MA', 'Massachusetts', 't');
INSERT INTO "public"."region" VALUES ('19023', '19', 'MI', 'Michigan', 't');
INSERT INTO "public"."region" VALUES ('19024', '19', 'MN', 'Minnesota', 't');
INSERT INTO "public"."region" VALUES ('19025', '19', 'MS', 'Mississippi', 't');
INSERT INTO "public"."region" VALUES ('19026', '19', 'MO', 'Missouri', 't');
INSERT INTO "public"."region" VALUES ('19027', '19', 'MT', 'Montana', 't');
INSERT INTO "public"."region" VALUES ('19028', '19', 'NE', 'Nebraska', 't');
INSERT INTO "public"."region" VALUES ('19029', '19', 'NV', 'Nevada', 't');
INSERT INTO "public"."region" VALUES ('19030', '19', 'NH', 'New Hampshire', 't');
INSERT INTO "public"."region" VALUES ('19031', '19', 'NJ', 'New Jersey', 't');
INSERT INTO "public"."region" VALUES ('19032', '19', 'NM', 'New Mexico', 't');
INSERT INTO "public"."region" VALUES ('19033', '19', 'NY', 'New York', 't');
INSERT INTO "public"."region" VALUES ('19034', '19', 'NC', 'North Carolina', 't');
INSERT INTO "public"."region" VALUES ('19035', '19', 'ND', 'North Dakota', 't');
INSERT INTO "public"."region" VALUES ('19036', '19', 'OH', 'Ohio', 't');
INSERT INTO "public"."region" VALUES ('19037', '19', 'OK', 'Oklahoma ', 't');
INSERT INTO "public"."region" VALUES ('19038', '19', 'OR', 'Oregon', 't');
INSERT INTO "public"."region" VALUES ('19039', '19', 'PA', 'Pennsylvania', 't');
INSERT INTO "public"."region" VALUES ('19040', '19', 'PR', 'Puerto Rico', 't');
INSERT INTO "public"."region" VALUES ('19041', '19', 'RI', 'Rhode Island', 't');
INSERT INTO "public"."region" VALUES ('19042', '19', 'SC', 'South Carolina', 't');
INSERT INTO "public"."region" VALUES ('19043', '19', 'SD', 'South Dakota', 't');
INSERT INTO "public"."region" VALUES ('19044', '19', 'TN', 'Tennessee', 't');
INSERT INTO "public"."region" VALUES ('19045', '19', 'TX', 'Texas', 't');
INSERT INTO "public"."region" VALUES ('19046', '19', 'UT', 'Utah', 't');
INSERT INTO "public"."region" VALUES ('19047', '19', 'VT', 'Vermont', 't');
INSERT INTO "public"."region" VALUES ('19048', '19', 'VA', 'Virginia', 't');
INSERT INTO "public"."region" VALUES ('19049', '19', 'WA', 'Washington', 't');
INSERT INTO "public"."region" VALUES ('19050', '19', 'WV', 'West Virginia', 't');
INSERT INTO "public"."region" VALUES ('19051', '19', 'WI', 'Wisconsin', 't');
INSERT INTO "public"."region" VALUES ('19052', '19', 'WY', 'Wyoming', 't');
INSERT INTO "public"."region" VALUES ('32001', '32', 'ACT', 'Australian Capital Territory', 't');
INSERT INTO "public"."region" VALUES ('32002', '32', 'NSW', 'New South Wales', 't');
INSERT INTO "public"."region" VALUES ('32003', '32', 'NT', 'Northern Territory', 't');
INSERT INTO "public"."region" VALUES ('32004', '32', 'QLD', 'Queensland', 't');
INSERT INTO "public"."region" VALUES ('32005', '32', 'SA', 'South Australia', 't');
INSERT INTO "public"."region" VALUES ('32006', '32', 'TAS', 'Tasmania', 't');
INSERT INTO "public"."region" VALUES ('32007', '32', 'VIC', 'Victoria', 't');
INSERT INTO "public"."region" VALUES ('32008', '32', 'WA', 'Western Australia', 't');
INSERT INTO "public"."region" VALUES ('144001', '144', 'MX-AGS', 'Aguascalientes', 't');
INSERT INTO "public"."region" VALUES ('144002', '144', 'MX-BCN', 'Baja California', 't');
INSERT INTO "public"."region" VALUES ('144003', '144', 'MX-BCS', 'Baja California Sur', 't');
INSERT INTO "public"."region" VALUES ('144004', '144', 'MX-CAM', 'Campeche', 't');
INSERT INTO "public"."region" VALUES ('144005', '144', 'MX-CHP', 'Chiapas', 't');
INSERT INTO "public"."region" VALUES ('144006', '144', 'MX-CHI', 'Chihuahua', 't');
INSERT INTO "public"."region" VALUES ('144007', '144', 'MX-COA', 'Coahuila', 't');
INSERT INTO "public"."region" VALUES ('144008', '144', 'MX-COL', 'Colima', 't');
INSERT INTO "public"."region" VALUES ('144009', '144', 'MX-DUR', 'Durango', 't');
INSERT INTO "public"."region" VALUES ('144010', '144', 'MX-GTO', 'Guanajuato', 't');
INSERT INTO "public"."region" VALUES ('144011', '144', 'MX-GRO', 'Guerrero', 't');
INSERT INTO "public"."region" VALUES ('144012', '144', 'MX-HGO', 'Hidalgo', 't');
INSERT INTO "public"."region" VALUES ('144013', '144', 'MX-JAL', 'Jalisco', 't');
INSERT INTO "public"."region" VALUES ('144014', '144', 'MX-MEX', 'Mexico', 't');
INSERT INTO "public"."region" VALUES ('144015', '144', 'MX-MIC', 'Michoacan', 't');
INSERT INTO "public"."region" VALUES ('144016', '144', 'MX-MOR', 'Morelos', 't');
INSERT INTO "public"."region" VALUES ('144017', '144', 'MX-NAY', 'Nayarit', 't');
INSERT INTO "public"."region" VALUES ('144018', '144', 'MX-NLE', 'Nuevo Leon', 't');
INSERT INTO "public"."region" VALUES ('144019', '144', 'MX-OAX', 'Oaxaca', 't');
INSERT INTO "public"."region" VALUES ('144020', '144', 'MX-PUE', 'Puebla', 't');
INSERT INTO "public"."region" VALUES ('144021', '144', 'MX-QRO', 'Queretaro', 't');
INSERT INTO "public"."region" VALUES ('144023', '144', 'MX-ROO', 'Quintana Roo', 't');
INSERT INTO "public"."region" VALUES ('144024', '144', 'MX-SLP', 'San Luis Potosí', 't');
INSERT INTO "public"."region" VALUES ('144025', '144', 'MX-SIN', 'Sinaloa', 't');
INSERT INTO "public"."region" VALUES ('144026', '144', 'MX-SON', 'Sonora', 't');
INSERT INTO "public"."region" VALUES ('144027', '144', 'MX-TAB', 'Tabasco', 't');
INSERT INTO "public"."region" VALUES ('144028', '144', 'MX-TAM', 'Tamaulipas', 't');
INSERT INTO "public"."region" VALUES ('144029', '144', 'MX-TLX', 'Tlaxcala', 't');
INSERT INTO "public"."region" VALUES ('144030', '144', 'MX-VER', 'Veracruz', 't');
INSERT INTO "public"."region" VALUES ('144031', '144', 'MX-YUC', 'Yucatan', 't');
INSERT INTO "public"."region" VALUES ('144032', '144', 'MX-ZAC', 'Zacatecas', 't');
INSERT INTO "public"."region" VALUES ('164001', '164', '01', 'Østfold', 't');
INSERT INTO "public"."region" VALUES ('164002', '164', '02', 'Akershus', 't');
INSERT INTO "public"."region" VALUES ('164003', '164', '03', 'Oslo', 't');
INSERT INTO "public"."region" VALUES ('164004', '164', '04', 'Hedmark', 't');
INSERT INTO "public"."region" VALUES ('164005', '164', '05', 'Oppland', 't');
INSERT INTO "public"."region" VALUES ('164006', '164', '06', 'Buskerud', 't');
INSERT INTO "public"."region" VALUES ('164007', '164', '07', 'Vestfold', 't');
INSERT INTO "public"."region" VALUES ('164008', '164', '08', 'Telemark', 't');
INSERT INTO "public"."region" VALUES ('164009', '164', '09', 'Aust-Agder', 't');
INSERT INTO "public"."region" VALUES ('164010', '164', '10', 'Vest-Agder', 't');
INSERT INTO "public"."region" VALUES ('164011', '164', '11', 'Rogaland', 't');
INSERT INTO "public"."region" VALUES ('164012', '164', '12', 'Hordaland', 't');
INSERT INTO "public"."region" VALUES ('164013', '164', '14', 'Sogn og Fjordane', 't');
INSERT INTO "public"."region" VALUES ('164014', '164', '15', 'Møre of Romsdal', 't');
INSERT INTO "public"."region" VALUES ('164015', '164', '16', 'Sør-Trøndelag', 't');
INSERT INTO "public"."region" VALUES ('164016', '164', '17', 'Nord-Trøndelag', 't');
INSERT INTO "public"."region" VALUES ('164017', '164', '18', 'Nordland', 't');
INSERT INTO "public"."region" VALUES ('164018', '164', '19', 'Troms', 't');
INSERT INTO "public"."region" VALUES ('164019', '164', '20', 'Finnmark', 't');
INSERT INTO "public"."region" VALUES ('202001', '202', 'AG', 'Aargau', 't');
INSERT INTO "public"."region" VALUES ('202002', '202', 'AR', 'Appenzell Ausserrhoden', 't');
INSERT INTO "public"."region" VALUES ('202003', '202', 'AI', 'Appenzell Innerrhoden', 't');
INSERT INTO "public"."region" VALUES ('202004', '202', 'BL', 'Basel-Landschaft', 't');
INSERT INTO "public"."region" VALUES ('202005', '202', 'BS', 'Basel-Stadt', 't');
INSERT INTO "public"."region" VALUES ('202006', '202', 'BE', 'Bern', 't');
INSERT INTO "public"."region" VALUES ('202007', '202', 'FR', 'Fribourg', 't');
INSERT INTO "public"."region" VALUES ('202008', '202', 'GE', 'Geneva', 't');
INSERT INTO "public"."region" VALUES ('202009', '202', 'GL', 'Glarus', 't');
INSERT INTO "public"."region" VALUES ('202010', '202', 'GR', 'Graubünden', 't');
INSERT INTO "public"."region" VALUES ('202011', '202', 'JU', 'Jura', 't');
INSERT INTO "public"."region" VALUES ('202012', '202', 'LU', 'Lucerne', 't');
INSERT INTO "public"."region" VALUES ('202013', '202', 'NE', 'Neuchâtel', 't');
INSERT INTO "public"."region" VALUES ('202014', '202', 'NW', 'Nidwalden', 't');
INSERT INTO "public"."region" VALUES ('202015', '202', 'OW', 'Obwalden', 't');
INSERT INTO "public"."region" VALUES ('202016', '202', 'SH', 'Schaffhausen', 't');
INSERT INTO "public"."region" VALUES ('202017', '202', 'SZ', 'Schwyz', 't');
INSERT INTO "public"."region" VALUES ('202018', '202', 'SO', 'Solothurn', 't');
INSERT INTO "public"."region" VALUES ('202019', '202', 'SG', 'St. Gallen', 't');
INSERT INTO "public"."region" VALUES ('202020', '202', 'TG', 'Thurgau', 't');
INSERT INTO "public"."region" VALUES ('202021', '202', 'TI', 'Ticino', 't');
INSERT INTO "public"."region" VALUES ('202022', '202', 'UR', 'Uri', 't');
INSERT INTO "public"."region" VALUES ('202023', '202', 'VS', 'Valais', 't');
INSERT INTO "public"."region" VALUES ('202024', '202', 'VD', 'Vaud', 't');
INSERT INTO "public"."region" VALUES ('202025', '202', 'ZG', 'Zug', 't');
INSERT INTO "public"."region" VALUES ('202026', '202', 'ZH', 'Zürich', 't');
INSERT INTO "public"."region" VALUES ('202027', '17', '01', 'Hà Nội', 't');
INSERT INTO "public"."region" VALUES ('202028', '17', '02', 'Hà Giang', 't');
INSERT INTO "public"."region" VALUES ('202029', '17', '04', 'Cao Bằng', 't');
INSERT INTO "public"."region" VALUES ('202030', '17', '06', 'Bắc Kạn', 't');
INSERT INTO "public"."region" VALUES ('202031', '17', '08', 'Tuyên Quang', 't');
INSERT INTO "public"."region" VALUES ('202032', '17', '10', 'Lào Cai', 't');
INSERT INTO "public"."region" VALUES ('202033', '17', '11', 'Điện Biên', 't');
INSERT INTO "public"."region" VALUES ('202034', '17', '12', 'Lai Châu', 't');
INSERT INTO "public"."region" VALUES ('202035', '17', '14', 'Sơn La', 't');
INSERT INTO "public"."region" VALUES ('202036', '17', '15', 'Yên Bái', 't');
INSERT INTO "public"."region" VALUES ('202037', '17', '17', 'Hòa Bình', 't');
INSERT INTO "public"."region" VALUES ('202038', '17', '19', 'Thái Nguyên', 't');
INSERT INTO "public"."region" VALUES ('202039', '17', '20', 'Lạng Sơn', 't');
INSERT INTO "public"."region" VALUES ('202040', '17', '22', 'Quảng Ninh', 't');
INSERT INTO "public"."region" VALUES ('202041', '17', '24', 'Bắc Giang', 't');
INSERT INTO "public"."region" VALUES ('202042', '17', '25', 'Phú Thọ', 't');
INSERT INTO "public"."region" VALUES ('202043', '17', '26', 'Vĩnh Phúc', 't');
INSERT INTO "public"."region" VALUES ('202044', '17', '27', 'Bắc Ninh', 't');
INSERT INTO "public"."region" VALUES ('202045', '17', '30', 'Hải Dương', 't');
INSERT INTO "public"."region" VALUES ('202046', '17', '31', 'Hải Phòng', 't');
INSERT INTO "public"."region" VALUES ('202047', '17', '33', 'Hưng Yên', 't');
INSERT INTO "public"."region" VALUES ('202048', '17', '34', 'Thái Bình', 't');
INSERT INTO "public"."region" VALUES ('202049', '17', '35', 'Hà Nam', 't');
INSERT INTO "public"."region" VALUES ('202050', '17', '36', 'Nam Định', 't');
INSERT INTO "public"."region" VALUES ('202051', '17', '37', 'Ninh Bình', 't');
INSERT INTO "public"."region" VALUES ('202052', '17', '38', 'Thanh Hóa', 't');
INSERT INTO "public"."region" VALUES ('202053', '17', '40', 'Nghệ An', 't');
INSERT INTO "public"."region" VALUES ('202054', '17', '42', 'Hà Tĩnh', 't');
INSERT INTO "public"."region" VALUES ('202055', '17', '44', 'Quảng Bình', 't');
INSERT INTO "public"."region" VALUES ('202056', '17', '45', 'Quảng Trị', 't');
INSERT INTO "public"."region" VALUES ('202057', '17', '46', 'Thừa Thiên Huế', 't');
INSERT INTO "public"."region" VALUES ('202058', '17', '48', 'Đà Nẵng', 't');
INSERT INTO "public"."region" VALUES ('202059', '17', '49', 'Quảng Nam', 't');
INSERT INTO "public"."region" VALUES ('202060', '17', '51', 'Quảng Ngãi', 't');
INSERT INTO "public"."region" VALUES ('202061', '17', '52', 'Bình Định', 't');
INSERT INTO "public"."region" VALUES ('202062', '17', '54', 'Phú Yên', 't');
INSERT INTO "public"."region" VALUES ('202063', '17', '56', 'Khánh Hòa', 't');
INSERT INTO "public"."region" VALUES ('202064', '17', '58', 'Ninh Thuận', 't');
INSERT INTO "public"."region" VALUES ('202065', '17', '60', 'Bình Thuận', 't');
INSERT INTO "public"."region" VALUES ('202066', '17', '62', 'Kon Tum', 't');
INSERT INTO "public"."region" VALUES ('202067', '17', '64', 'Gia Lai', 't');
INSERT INTO "public"."region" VALUES ('202068', '17', '66', 'Đắk Lắk', 't');
INSERT INTO "public"."region" VALUES ('202069', '17', '67', 'Đắk Nông', 't');
INSERT INTO "public"."region" VALUES ('202070', '17', '68', 'Lâm Đồng', 't');
INSERT INTO "public"."region" VALUES ('202071', '17', '70', 'Bình Phước', 't');
INSERT INTO "public"."region" VALUES ('202072', '17', '72', 'Tây Ninh', 't');
INSERT INTO "public"."region" VALUES ('202073', '17', '74', 'Bình Dương', 't');
INSERT INTO "public"."region" VALUES ('202074', '17', '75', 'Đồng Nai', 't');
INSERT INTO "public"."region" VALUES ('202075', '17', '77', 'Bà Rịa - Vũng Tàu', 't');
INSERT INTO "public"."region" VALUES ('202076', '17', '79', 'Hồ Chí Minh', 't');
INSERT INTO "public"."region" VALUES ('202077', '17', '80', 'Long An', 't');
INSERT INTO "public"."region" VALUES ('202078', '17', '82', 'Tiền Giang', 't');
INSERT INTO "public"."region" VALUES ('202079', '17', '83', 'Bến Tre', 't');
INSERT INTO "public"."region" VALUES ('202080', '17', '84', 'Trà Vinh', 't');
INSERT INTO "public"."region" VALUES ('202081', '17', '86', 'Vĩnh Long', 't');
INSERT INTO "public"."region" VALUES ('202082', '17', '87', 'Đồng Tháp', 't');
INSERT INTO "public"."region" VALUES ('202083', '17', '89', 'An Giang', 't');
INSERT INTO "public"."region" VALUES ('202084', '17', '91', 'Kiên Giang', 't');
INSERT INTO "public"."region" VALUES ('202085', '17', '92', 'Cần Thơ', 't');
INSERT INTO "public"."region" VALUES ('202086', '17', '93', 'Hậu Giang', 't');
INSERT INTO "public"."region" VALUES ('202087', '17', '94', 'Sóc Trăng', 't');
INSERT INTO "public"."region" VALUES ('202088', '17', '95', 'Bạc Liêu', 't');
INSERT INTO "public"."region" VALUES ('202089', '17', '96', 'Cà Mau', 't');

-- ----------------------------
-- Alter Sequences Owned By 
-- ----------------------------

-- ----------------------------
-- Indexes structure for table region
-- ----------------------------
CREATE INDEX "ix_11fb3e42" ON "public"."region" USING btree (countryid, active_);
CREATE INDEX "ix_16d87ca7" ON "public"."region" USING btree (countryid);
CREATE INDEX "ix_2d9a426f" ON "public"."region" USING btree (active_);
CREATE UNIQUE INDEX "ix_a2635f5c" ON "public"."region" USING btree (countryid, regioncode);

-- ----------------------------
-- Primary Key structure for table region
-- ----------------------------
ALTER TABLE "public"."region" ADD PRIMARY KEY ("regionid");
